name: Blog Deploy

on:
  push:
    branches: ['chore/deploy-workflow']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout datas
        uses: actions/checkout@v3

      - name: git config
        env:
          USER_NAME: ${{ github.event.head_commit.author.name }}
          USER_EMAIL: ${{ github.event.head_commit.author.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run deploy
