name: Blog Deploy

on:
  push:
    branches: ['chore/deploy-workflow']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout datas
        uses: actions/checkout@v3

      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run deploy
